### ISSUE TITLE
Actividad 5 Cuadro comparativo - Blanca Estela 

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Blanca-estela-valerio-rivero#1]
[Tipos de texto-cuadro comparativo..pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Blanca-estela-valerio-rivero/files/9642562/Tipos.de.texto-cuadro.comparativo.pdf)

**Comment by AmeliReyesHernandez** [comment]
18 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
